# Generated by Django 3.1.3 on 2021-01-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210120_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshop',
            name='is_favorites',
            field=models.BooleanField(default=False),
        ),
    ]
